### ISSUE TITLE
Airline not-current windows are being shown with multiple ^ chars

### ISSUE THREAD

**Issue by jclsn** [pineapplegiant/spacedirt-theme#66]
I were just trying to use [this plugin](https://github.com/Roy-Orbison/airline-colour-splits), because I do not like the | as vertical fillchars and have this [issue](https://github.com/Roy-Orbison/airline-colour-splits/issues/1). 

Seems like it is related to the Spaceduck dev branch and StatusLine and StatusLineNC having the same values. I could fix it by changing line 250
```vim
call s:hi('StatusLineNC',     s:palette.bg,          s:palette.grey,       'reverse'  )
```
to 
```vim
call s:hi('StatusLineNC',     s:palette.bg,          s:palette.grey,       'underline'  )
```

there is probably a better solution though.

**Comment by pineapplegiant** [comment]
[This PR fixes this issue.](https://github.com/pineapplegiant/spaceduck/pull/67) 🥇
